import { getToken, linkOptions } from "@/lib/apolloLinkOptions";
import { initApollo } from "@/lib/initApollo";
import { ThemeSwitcher } from "@/modules/shared/ThemeSwitcher";
import { gql } from "@apollo/client";
import type { Metadata } from "next";
import { User, UserVariables } from "./__generated__/page.generated";

export const dynamic = "force-dynamic";

export const metadata: Metadata = {
  title: "Web",
  description: "Generated by create next app",
  viewport: "width=device-width, initial-scale=1",
  icons: {
    icon: "/favicon.ico",
  },
};

export default async function Home() {
  const apolloClient = initApollo(linkOptions, {}, { getToken });

  const { data, loading } = await apolloClient.query<User, UserVariables>({
    query: gql`
      query User {
        user(
          userId: "VXNlcjo0NjNiOGJiNy02Y2Y2LTRhOTctYTY2NS1hYjU3MzBiNjliYTI="
        ) {
          id
          email
          firstName
          lastName
          createdAt
          updatedAt
        }
      }
    `,
  });

  return (
    <main>
      <ThemeSwitcher />
      {!loading && data.user && <pre>{JSON.stringify(data.user, null, 2)}</pre>}
    </main>
  );
}
