extend schema
  @link(url: "https://specs.apollo.dev/federation/v2.3", import: ["@key", "@shareable", "@inaccessible", "@tag", "@provides", "@requires", "@external", "@extends", "@override"])

type Comment implements Node {
  id: ID!
  body: String!
  user: User!
  createdAt: DateTime!
  updatedAt: DateTime!
}

scalar DateTime

interface Node {
  id: ID!
}

type Query {
  node(id: ID!): Node @shareable
  nodes(ids: [ID!]!): [Node]! @shareable
}

type User
  @key(fields: "id")
  @extends
{
  id: ID! @external
  comments: [Comment!]!
}
