directive @inaccessible on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION

directive @link(import: [link__Import], url: String!) on SCHEMA

directive @override(from: String!) on FIELD_DEFINITION

directive @shareable on FIELD_DEFINITION | OBJECT

type Comment implements Node {
  id: ID!
  body: String!
  user: User!
  createdAt: DateTime!
  updatedAt: DateTime!
}

scalar DateTime

interface Node {
  id: ID!
}

type Query {
  node(id: ID!): Node
  nodes(ids: [ID!]!): [Node]!
}

type User
  @key(fields: "id")
  @extends
{
  id: ID! @external
  comments: [Comment!]!
}

scalar link__Import